import { v } from "convex/values";
import { mutation } from "./_generated/server";

export const addAlgorithms401to600 = mutation({
  args: {},
  handler: async (ctx) => {
    const existingCount = await ctx.db.query("algorithms").take(1000);
    console.log(`Found ${existingCount.length} existing algorithms`);

    const createAlgorithm = (
      num: number,
      name: string,
      category: string,
      domain: string,
      difficulty: string,
      timeComplexity: { best: string; average: string; worst: string },
      spaceComplexity: string,
      visualizationType: string
    ) => ({
      name,
      slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      category,
      domain,
      description: `${name} - An advanced algorithm in the ${category} category`,
      intuition: `${name} is used for efficient problem-solving in ${domain}`,
      pseudocode: `// ${name} pseudocode\nfunction ${name.replace(/[^a-zA-Z0-9]/g, "")}() {\n  // Implementation\n}`,
      implementation: `// ${name} implementation\nfunction ${name.replace(/[^a-zA-Z0-9]/g, "")}() {\n  // Code here\n  return result;\n}`,
      language: "JavaScript",
      timeComplexity,
      spaceComplexity,
      applications: [`${category} optimization`, `${domain} problems`, "Research applications"],
      advantages: ["Efficient performance", "Scalable solution", "Well-studied approach"],
      disadvantages: ["May require optimization", "Complexity trade-offs"],
      tags: [category.toLowerCase(), domain.toLowerCase().replace(/\s+/g, "-"), difficulty.toLowerCase()],
      difficulty,
      visualizationType,
      relatedAlgorithms: [],
      researchReferences: [`${name} Reference`, `${category} Theory`],
    });

    const allAlgorithms = [
      // 21. Advanced Tree Algorithms (20) - Algorithms 201-220
      createAlgorithm(201, "AVL Tree Rotation Algorithm", "Tree", "Data Structures", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "tree"),
      createAlgorithm(202, "Red-Black Tree Insertion", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "tree"),
      createAlgorithm(203, "Red-Black Tree Deletion", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "tree"),
      createAlgorithm(204, "B-Tree Insertion", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(205, "B-Tree Deletion", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(206, "B+ Tree Search", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(207, "Splay Tree Operation", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(208, "Treap Insertion", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(209, "Cartesian Tree Construction", "Tree", "Data Structures", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(210, "Segment Tree Construction", "Tree", "Data Structures", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(211, "Lazy Propagation", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(212, "Fenwick Tree Update", "Tree", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(213, "Lowest Common Ancestor (Binary Lifting)", "Tree", "Graph Algorithms", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n log n)", "tree"),
      createAlgorithm(214, "Euler Tour Technique", "Tree", "Graph Algorithms", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(215, "Heavy Light Decomposition", "Tree", "Graph Algorithms", "Expert",
        { best: "O(log² n)", average: "O(log² n)", worst: "O(log² n)" }, "O(n)", "tree"),
      createAlgorithm(216, "Centroid Decomposition", "Tree", "Graph Algorithms", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n log n)", "tree"),
      createAlgorithm(217, "Tree Isomorphism Algorithm", "Tree", "Graph Algorithms", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(218, "Tree Diameter Algorithm", "Tree", "Graph Algorithms", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(219, "Prüfer Code Algorithm", "Tree", "Graph Algorithms", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(220, "Huffman Tree Construction", "Tree", "Compression", "Intermediate",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "tree"),

      // 22. Advanced Graph Theory Algorithms (25) - Algorithms 221-245
      createAlgorithm(221, "Tarjan's SCC Algorithm", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(222, "Kosaraju's SCC Algorithm", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(223, "Gabow's Algorithm", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(224, "Edmonds' Arborescence", "Graph", "Graph Algorithms", "Expert",
        { best: "O(E log V)", average: "O(E log V)", worst: "O(E log V)" }, "O(V)", "graph"),
      createAlgorithm(225, "Stoer–Wagner Min Cut", "Graph", "Graph Algorithms", "Expert",
        { best: "O(V³)", average: "O(V³)", worst: "O(V³)" }, "O(V²)", "graph"),
      createAlgorithm(226, "Gomory–Hu Tree", "Graph", "Graph Algorithms", "Expert",
        { best: "O(V⁴)", average: "O(V⁴)", worst: "O(V⁴)" }, "O(V²)", "graph"),
      createAlgorithm(227, "Suurballe's Algorithm", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(E log V)", average: "O(E log V)", worst: "O(E log V)" }, "O(V)", "graph"),
      createAlgorithm(228, "Yen's K-Shortest Paths", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(K·V³)", average: "O(K·V³)", worst: "O(K·V³)" }, "O(V²)", "graph"),
      createAlgorithm(229, "Dial's Algorithm", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(E + V·W)", average: "O(E + V·W)", worst: "O(E + V·W)" }, "O(V + W)", "graph"),
      createAlgorithm(230, "Thorup's Algorithm", "Graph", "Graph Algorithms", "Expert",
        { best: "O(E)", average: "O(E)", worst: "O(E)" }, "O(V)", "graph"),
      createAlgorithm(231, "Push-Relabel with Heuristics", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V²E)", average: "O(V²E)", worst: "O(V³)" }, "O(V)", "graph"),
      createAlgorithm(232, "Goldberg–Tarjan Algorithm", "Graph", "Graph Algorithms", "Expert",
        { best: "O(VE log(V²/E))", average: "O(VE log(V²/E))", worst: "O(VE log(V²/E))" }, "O(V)", "graph"),
      createAlgorithm(233, "Edmonds–Karp (Optimized)", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(VE²)", average: "O(VE²)", worst: "O(VE²)" }, "O(V)", "graph"),
      createAlgorithm(234, "Maximum Closure Problem", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V³)", average: "O(V³)", worst: "O(V³)" }, "O(V²)", "graph"),
      createAlgorithm(235, "Directed Acyclic Graph Shortest Path", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(236, "Minimum Mean Cycle", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(VE)", average: "O(VE)", worst: "O(VE)" }, "O(V)", "graph"),
      createAlgorithm(237, "Graph Coloring (Welsh–Powell)", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(V²)", average: "O(V²)", worst: "O(V²)" }, "O(V)", "graph"),
      createAlgorithm(238, "Chordal Graph Recognition", "Graph", "Graph Algorithms", "Advanced",
        { best: "O(V + E)", average: "O(V + E)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(239, "Planarity Testing Algorithm", "Graph", "Graph Algorithms", "Expert",
        { best: "O(V)", average: "O(V)", worst: "O(V)" }, "O(V)", "graph"),
      createAlgorithm(240, "Graph Isomorphism (Weisfeiler–Lehman)", "Graph", "Graph Algorithms", "Expert",
        { best: "O(V log V)", average: "O(V log V)", worst: "O(V log V)" }, "O(V)", "graph"),
      createAlgorithm(241, "Line Graph Construction", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(E²)", average: "O(E²)", worst: "O(E²)" }, "O(E²)", "graph"),
      createAlgorithm(242, "Random Walk on Graph", "Graph", "Graph Algorithms", "Beginner",
        { best: "O(k)", average: "O(k)", worst: "O(k)" }, "O(V)", "graph"),
      createAlgorithm(243, "PageRank Algorithm", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(k·E)", average: "O(k·E)", worst: "O(k·E)" }, "O(V)", "graph"),
      createAlgorithm(244, "HITS Algorithm", "Graph", "Graph Algorithms", "Intermediate",
        { best: "O(k·E)", average: "O(k·E)", worst: "O(k·E)" }, "O(V)", "graph"),
      createAlgorithm(245, "Label Propagation Algorithm", "Graph", "Machine Learning", "Intermediate",
        { best: "O(k·E)", average: "O(k·E)", worst: "O(k·E)" }, "O(V)", "graph"),

      // 23. Numerical & Mathematical Algorithms (20) - Algorithms 246-265
      createAlgorithm(246, "Euclidean Algorithm", "Mathematical", "Number Theory", "Beginner",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(247, "Extended Euclidean Algorithm", "Mathematical", "Number Theory", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(248, "Modular Exponentiation", "Mathematical", "Number Theory", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(249, "Fast Power Algorithm", "Mathematical", "Number Theory", "Beginner",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(250, "Chinese Remainder Theorem Algorithm", "Mathematical", "Number Theory", "Advanced",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
      createAlgorithm(251, "Sieve of Eratosthenes", "Mathematical", "Number Theory", "Beginner",
        { best: "O(n log log n)", average: "O(n log log n)", worst: "O(n log log n)" }, "O(n)", "array"),
      createAlgorithm(252, "Segmented Sieve", "Mathematical", "Number Theory", "Intermediate",
        { best: "O(n log log n)", average: "O(n log log n)", worst: "O(n log log n)" }, "O(√n)", "array"),
      createAlgorithm(253, "Miller–Rabin Primality Test", "Mathematical", "Number Theory", "Advanced",
        { best: "O(k log³ n)", average: "O(k log³ n)", worst: "O(k log³ n)" }, "O(1)", "array"),
      createAlgorithm(254, "Fermat Primality Test", "Mathematical", "Number Theory", "Intermediate",
        { best: "O(k log n)", average: "O(k log n)", worst: "O(k log n)" }, "O(1)", "array"),
      createAlgorithm(255, "Pollard's Rho Algorithm", "Mathematical", "Number Theory", "Advanced",
        { best: "O(n^(1/4))", average: "O(n^(1/4))", worst: "O(n^(1/4))" }, "O(1)", "array"),
      createAlgorithm(256, "Newton–Raphson Method", "Mathematical", "Numerical Analysis", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(257, "Bisection Method", "Mathematical", "Numerical Analysis", "Beginner",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(258, "Secant Method", "Mathematical", "Numerical Analysis", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(259, "Gaussian Elimination", "Mathematical", "Linear Algebra", "Intermediate",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(260, "LU Decomposition", "Mathematical", "Linear Algebra", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(261, "Cholesky Decomposition", "Mathematical", "Linear Algebra", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(262, "Fast Matrix Exponentiation", "Mathematical", "Linear Algebra", "Intermediate",
        { best: "O(n³ log k)", average: "O(n³ log k)", worst: "O(n³ log k)" }, "O(n²)", "array"),
      createAlgorithm(263, "Karatsuba Multiplication", "Mathematical", "Number Theory", "Advanced",
        { best: "O(n^1.58)", average: "O(n^1.58)", worst: "O(n^1.58)" }, "O(n)", "array"),
      createAlgorithm(264, "Toom–Cook Multiplication", "Mathematical", "Number Theory", "Expert",
        { best: "O(n^1.46)", average: "O(n^1.46)", worst: "O(n^1.46)" }, "O(n)", "array"),
      createAlgorithm(265, "Fast Fourier Multiplication", "Mathematical", "Number Theory", "Expert",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),

      // 24. Optimization Algorithms (20) - Algorithms 266-285
      createAlgorithm(266, "Linear Programming (Simplex)", "Optimization", "Operations Research", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "Exponential" }, "O(n²)", "array"),
      createAlgorithm(267, "Dual Simplex Algorithm", "Optimization", "Operations Research", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "Exponential" }, "O(n²)", "array"),
      createAlgorithm(268, "Interior Point Method", "Optimization", "Operations Research", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(269, "Cutting Plane Method", "Optimization", "Operations Research", "Expert",
        { best: "O(2^n)", average: "O(2^n)", worst: "O(2^n)" }, "O(n)", "array"),
      createAlgorithm(270, "Gradient Descent", "Optimization", "Machine Learning", "Beginner",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(271, "Stochastic Gradient Descent", "Optimization", "Machine Learning", "Intermediate",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(272, "Newton's Optimization Method", "Optimization", "Machine Learning", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(273, "Conjugate Gradient Method", "Optimization", "Machine Learning", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(274, "Lagrangian Relaxation", "Optimization", "Operations Research", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(275, "Simulated Annealing", "Optimization", "Metaheuristics", "Intermediate",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(276, "Genetic Algorithm", "Optimization", "Metaheuristics", "Intermediate",
        { best: "O(k·p·n)", average: "O(k·p·n)", worst: "O(k·p·n)" }, "O(p·n)", "array"),
      createAlgorithm(277, "Particle Swarm Optimization", "Optimization", "Metaheuristics", "Intermediate",
        { best: "O(k·p·n)", average: "O(k·p·n)", worst: "O(k·p·n)" }, "O(p·n)", "array"),
      createAlgorithm(278, "Ant Colony Optimization", "Optimization", "Metaheuristics", "Advanced",
        { best: "O(k·n²)", average: "O(k·n²)", worst: "O(k·n²)" }, "O(n²)", "array"),
      createAlgorithm(279, "Tabu Search", "Optimization", "Metaheuristics", "Intermediate",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(280, "Hill Climbing", "Optimization", "Metaheuristics", "Beginner",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(281, "Coordinate Descent", "Optimization", "Machine Learning", "Intermediate",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(282, "Trust Region Method", "Optimization", "Machine Learning", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(283, "Nelder–Mead Algorithm", "Optimization", "Numerical Analysis", "Intermediate",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(284, "Golden Section Search", "Optimization", "Numerical Analysis", "Beginner",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(285, "Branch and Cut", "Optimization", "Operations Research", "Expert",
        { best: "O(2^n)", average: "O(2^n)", worst: "O(2^n)" }, "O(n)", "tree"),

      // 25. Artificial Intelligence Algorithms (25) - Algorithms 286-310
      createAlgorithm(286, "Minimax Algorithm", "AI", "Game Theory", "Intermediate",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(bd)", "tree"),
      createAlgorithm(287, "Alpha–Beta Pruning", "AI", "Game Theory", "Intermediate",
        { best: "O(b^(d/2))", average: "O(b^(3d/4))", worst: "O(b^d)" }, "O(d)", "tree"),
      createAlgorithm(288, "Expectimax Algorithm", "AI", "Game Theory", "Advanced",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(bd)", "tree"),
      createAlgorithm(289, "Greedy Best-First Search", "AI", "Search Algorithms", "Intermediate",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(b^d)", "graph"),
      createAlgorithm(290, "Iterative Deepening DFS", "AI", "Search Algorithms", "Intermediate",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(d)", "graph"),
      createAlgorithm(291, "IDA* Algorithm", "AI", "Search Algorithms", "Advanced",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(d)", "graph"),
      createAlgorithm(292, "AO* Algorithm", "AI", "Search Algorithms", "Advanced",
        { best: "O(b^d)", average: "O(b^d)", worst: "O(b^d)" }, "O(b^d)", "graph"),
      createAlgorithm(293, "Constraint Propagation", "AI", "Constraint Satisfaction", "Intermediate",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n²)", "graph"),
      createAlgorithm(294, "Arc Consistency (AC-3)", "AI", "Constraint Satisfaction", "Intermediate",
        { best: "O(ed³)", average: "O(ed³)", worst: "O(ed³)" }, "O(e)", "graph"),
      createAlgorithm(295, "Backjumping Algorithm", "AI", "Constraint Satisfaction", "Advanced",
        { best: "O(d^n)", average: "O(d^n)", worst: "O(d^n)" }, "O(n)", "tree"),
      createAlgorithm(296, "Forward Checking", "AI", "Constraint Satisfaction", "Intermediate",
        { best: "O(d^n)", average: "O(d^n)", worst: "O(d^n)" }, "O(nd)", "tree"),
      createAlgorithm(297, "Bayesian Inference Algorithm", "AI", "Probabilistic Reasoning", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(2^n)" }, "O(n)", "graph"),
      createAlgorithm(298, "Hidden Markov Model (Viterbi)", "AI", "Probabilistic Reasoning", "Advanced",
        { best: "O(n·s²)", average: "O(n·s²)", worst: "O(n·s²)" }, "O(n·s)", "array"),
      createAlgorithm(299, "Kalman Filter", "AI", "Probabilistic Reasoning", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(300, "Particle Filter", "AI", "Probabilistic Reasoning", "Advanced",
        { best: "O(p·n)", average: "O(p·n)", worst: "O(p·n)" }, "O(p·n)", "array"),
      createAlgorithm(301, "Q-Learning", "AI", "Reinforcement Learning", "Intermediate",
        { best: "O(k·s·a)", average: "O(k·s·a)", worst: "O(k·s·a)" }, "O(s·a)", "array"),
      createAlgorithm(302, "SARSA Algorithm", "AI", "Reinforcement Learning", "Intermediate",
        { best: "O(k·s·a)", average: "O(k·s·a)", worst: "O(k·s·a)" }, "O(s·a)", "array"),
      createAlgorithm(303, "Policy Iteration", "AI", "Reinforcement Learning", "Advanced",
        { best: "O(s²·a)", average: "O(s²·a)", worst: "O(s³)" }, "O(s²)", "array"),
      createAlgorithm(304, "Value Iteration", "AI", "Reinforcement Learning", "Advanced",
        { best: "O(s²·a)", average: "O(s²·a)", worst: "O(s²·a)" }, "O(s)", "array"),
      createAlgorithm(305, "Monte Carlo Tree Search", "AI", "Game Theory", "Advanced",
        { best: "O(k·log n)", average: "O(k·log n)", worst: "O(k·n)" }, "O(n)", "tree"),
      createAlgorithm(306, "Neural Network Backpropagation", "AI", "Machine Learning", "Intermediate",
        { best: "O(n·w)", average: "O(n·w)", worst: "O(n·w)" }, "O(w)", "array"),
      createAlgorithm(307, "Hebbian Learning", "AI", "Machine Learning", "Beginner",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n²)", "array"),
      createAlgorithm(308, "Perceptron Learning", "AI", "Machine Learning", "Beginner",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(309, "Decision Tree Learning", "AI", "Machine Learning", "Intermediate",
        { best: "O(n·m·log m)", average: "O(n·m·log m)", worst: "O(n·m·log m)" }, "O(n·m)", "tree"),
      createAlgorithm(310, "Random Forest Algorithm", "AI", "Machine Learning", "Advanced",
        { best: "O(t·n·m·log m)", average: "O(t·n·m·log m)", worst: "O(t·n·m·log m)" }, "O(t·n·m)", "tree"),

      // 26. Machine Learning Core Algorithms (25) - Algorithms 311-335
      createAlgorithm(311, "Linear Regression", "Machine Learning", "Supervised Learning", "Beginner",
        { best: "O(n·m²)", average: "O(n·m²)", worst: "O(n·m²)" }, "O(m²)", "array"),
      createAlgorithm(312, "Logistic Regression", "Machine Learning", "Supervised Learning", "Beginner",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(m)", "array"),
      createAlgorithm(313, "Support Vector Machine", "Machine Learning", "Supervised Learning", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n)", "array"),
      createAlgorithm(314, "Naive Bayes Classifier", "Machine Learning", "Supervised Learning", "Beginner",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(c·m)", "array"),
      createAlgorithm(315, "K-Nearest Neighbors", "Machine Learning", "Supervised Learning", "Beginner",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(316, "K-Means Clustering", "Machine Learning", "Unsupervised Learning", "Beginner",
        { best: "O(k·n·m·i)", average: "O(k·n·m·i)", worst: "O(k·n·m·i)" }, "O(k·m)", "array"),
      createAlgorithm(317, "Hierarchical Clustering", "Machine Learning", "Unsupervised Learning", "Intermediate",
        { best: "O(n²·log n)", average: "O(n²·log n)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(318, "DBSCAN Algorithm", "Machine Learning", "Unsupervised Learning", "Intermediate",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(319, "Expectation–Maximization", "Machine Learning", "Unsupervised Learning", "Advanced",
        { best: "O(k·n·m²)", average: "O(k·n·m²)", worst: "O(k·n·m²)" }, "O(k·m²)", "array"),
      createAlgorithm(320, "Principal Component Analysis", "Machine Learning", "Dimensionality Reduction", "Intermediate",
        { best: "O(n·m²)", average: "O(n·m²)", worst: "O(n·m²)" }, "O(m²)", "array"),
      createAlgorithm(321, "Independent Component Analysis", "Machine Learning", "Dimensionality Reduction", "Advanced",
        { best: "O(k·n·m²)", average: "O(k·n·m²)", worst: "O(k·n·m²)" }, "O(m²)", "array"),
      createAlgorithm(322, "Linear Discriminant Analysis", "Machine Learning", "Dimensionality Reduction", "Intermediate",
        { best: "O(n·m²)", average: "O(n·m²)", worst: "O(n·m²)" }, "O(m²)", "array"),
      createAlgorithm(323, "Gradient Boosting", "Machine Learning", "Ensemble Learning", "Advanced",
        { best: "O(t·n·m·log m)", average: "O(t·n·m·log m)", worst: "O(t·n·m·log m)" }, "O(t·m)", "tree"),
      createAlgorithm(324, "AdaBoost", "Machine Learning", "Ensemble Learning", "Intermediate",
        { best: "O(t·n·m)", average: "O(t·n·m)", worst: "O(t·n·m)" }, "O(t·m)", "array"),
      createAlgorithm(325, "XGBoost", "Machine Learning", "Ensemble Learning", "Advanced",
        { best: "O(t·n·m·log m)", average: "O(t·n·m·log m)", worst: "O(t·n·m·log m)" }, "O(t·m)", "tree"),
      createAlgorithm(326, "LightGBM", "Machine Learning", "Ensemble Learning", "Advanced",
        { best: "O(t·n·m)", average: "O(t·n·m)", worst: "O(t·n·m·log m)" }, "O(t·m)", "tree"),
      createAlgorithm(327, "CatBoost", "Machine Learning", "Ensemble Learning", "Advanced",
        { best: "O(t·n·m·log m)", average: "O(t·n·m·log m)", worst: "O(t·n·m·log m)" }, "O(t·m)", "tree"),
      createAlgorithm(328, "Isolation Forest", "Machine Learning", "Anomaly Detection", "Intermediate",
        { best: "O(t·n·log n)", average: "O(t·n·log n)", worst: "O(t·n²)" }, "O(t·n)", "tree"),
      createAlgorithm(329, "One-Class SVM", "Machine Learning", "Anomaly Detection", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n)", "array"),
      createAlgorithm(330, "Apriori Algorithm", "Machine Learning", "Association Rules", "Intermediate",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(2^m)" }, "O(k·m)", "array"),
      createAlgorithm(331, "FP-Growth Algorithm", "Machine Learning", "Association Rules", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m·k)" }, "O(n·m)", "tree"),
      createAlgorithm(332, "Collaborative Filtering", "Machine Learning", "Recommendation Systems", "Intermediate",
        { best: "O(u·i)", average: "O(u·i)", worst: "O(u·i·k)" }, "O(u·i)", "array"),
      createAlgorithm(333, "Matrix Factorization", "Machine Learning", "Recommendation Systems", "Advanced",
        { best: "O(k·r·(u+i))", average: "O(k·r·(u+i))", worst: "O(k·r·(u+i))" }, "O(r·(u+i))", "array"),
      createAlgorithm(334, "ALS Algorithm", "Machine Learning", "Recommendation Systems", "Advanced",
        { best: "O(k·r³·(u+i))", average: "O(k·r³·(u+i))", worst: "O(k·r³·(u+i))" }, "O(r·(u+i))", "array"),
      createAlgorithm(335, "Topic Modeling (LDA)", "Machine Learning", "Natural Language Processing", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(t·v)", "array"),

      // 27. Operating Systems Algorithms (15) - Algorithms 336-350
      createAlgorithm(336, "FCFS Scheduling", "Operating Systems", "CPU Scheduling", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(337, "Shortest Job First", "Operating Systems", "CPU Scheduling", "Beginner",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
      createAlgorithm(338, "Priority Scheduling", "Operating Systems", "CPU Scheduling", "Beginner",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
      createAlgorithm(339, "Round Robin Scheduling", "Operating Systems", "CPU Scheduling", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(340, "Multilevel Queue Scheduling", "Operating Systems", "CPU Scheduling", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(341, "Multilevel Feedback Queue", "Operating Systems", "CPU Scheduling", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(342, "Banker's Algorithm", "Operating Systems", "Deadlock Avoidance", "Intermediate",
        { best: "O(n²·m)", average: "O(n²·m)", worst: "O(n²·m)" }, "O(n·m)", "array"),
      createAlgorithm(343, "Deadlock Detection Algorithm", "Operating Systems", "Deadlock Detection", "Intermediate",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n²)", "graph"),
      createAlgorithm(344, "Deadlock Prevention Algorithm", "Operating Systems", "Deadlock Prevention", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(345, "Page Replacement (FIFO)", "Operating Systems", "Memory Management", "Beginner",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(f)", "array"),
      createAlgorithm(346, "Page Replacement (LRU)", "Operating Systems", "Memory Management", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(f)", "array"),
      createAlgorithm(347, "Page Replacement (Optimal)", "Operating Systems", "Memory Management", "Beginner",
        { best: "O(f·p)", average: "O(f·p)", worst: "O(f·p)" }, "O(f)", "array"),
      createAlgorithm(348, "Clock Replacement Algorithm", "Operating Systems", "Memory Management", "Intermediate",
        { best: "O(1)", average: "O(f)", worst: "O(f)" }, "O(f)", "array"),
      createAlgorithm(349, "Disk Scheduling (SCAN)", "Operating Systems", "Disk Scheduling", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(350, "Disk Scheduling (C-LOOK)", "Operating Systems", "Disk Scheduling", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),

      // 28. Database & Data Mining Algorithms (15) - Algorithms 351-365
      createAlgorithm(351, "B-Tree Indexing", "Database", "Database Systems", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(352, "Hash Indexing", "Database", "Database Systems", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(353, "Query Optimization Algorithm", "Database", "Database Systems", "Advanced",
        { best: "O(n)", average: "O(n²)", worst: "O(n!)" }, "O(n)", "tree"),
      createAlgorithm(354, "Cost-Based Optimization", "Database", "Database Systems", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n)", "tree"),
      createAlgorithm(355, "Join Ordering Algorithm", "Database", "Database Systems", "Advanced",
        { best: "O(n!)", average: "O(n!)", worst: "O(n!)" }, "O(n)", "tree"),
      createAlgorithm(356, "Sort-Merge Join", "Database", "Database Systems", "Intermediate",
        { best: "O(n log n + m log m)", average: "O(n log n + m log m)", worst: "O(n log n + m log m)" }, "O(n+m)", "array"),
      createAlgorithm(357, "Hash Join", "Database", "Database Systems", "Intermediate",
        { best: "O(n + m)", average: "O(n + m)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(358, "Nested Loop Join", "Database", "Database Systems", "Beginner",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(1)", "array"),
      createAlgorithm(359, "Transaction Scheduling", "Database", "Database Systems", "Advanced",
        { best: "O(n)", average: "O(n log n)", worst: "O(n²)" }, "O(n)", "graph"),
      createAlgorithm(360, "Two-Phase Locking", "Database", "Database Systems", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(361, "Timestamp Ordering", "Database", "Database Systems", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "array"),
      createAlgorithm(362, "MVCC Algorithm", "Database", "Database Systems", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(363, "Apriori-TID", "Data Mining", "Association Rules", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(2^m)" }, "O(n·m)", "array"),
      createAlgorithm(364, "Eclat Algorithm", "Data Mining", "Association Rules", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m·k)" }, "O(n·m)", "array"),
      createAlgorithm(365, "Sequential Pattern Mining", "Data Mining", "Pattern Mining", "Advanced",
        { best: "O(n·m·k)", average: "O(n·m·k)", worst: "O(2^m)" }, "O(n·m)", "array"),

      // 29. Networking & Distributed Systems (15) - Algorithms 366-380
      createAlgorithm(366, "Distance Vector Routing", "Networking", "Routing Protocols", "Intermediate",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "graph"),
      createAlgorithm(367, "Link State Routing", "Networking", "Routing Protocols", "Advanced",
        { best: "O(E log V)", average: "O(E log V)", worst: "O(E log V)" }, "O(V²)", "graph"),
      createAlgorithm(368, "Dijkstra Routing Algorithm", "Networking", "Routing Protocols", "Intermediate",
        { best: "O((V + E) log V)", average: "O((V + E) log V)", worst: "O((V + E) log V)" }, "O(V)", "graph"),
      createAlgorithm(369, "Bellman–Ford Routing", "Networking", "Routing Protocols", "Intermediate",
        { best: "O(VE)", average: "O(VE)", worst: "O(VE)" }, "O(V)", "graph"),
      createAlgorithm(370, "Spanning Tree Protocol", "Networking", "Network Management", "Intermediate",
        { best: "O(E log V)", average: "O(E log V)", worst: "O(E log V)" }, "O(V)", "graph"),
      createAlgorithm(371, "Flooding Algorithm", "Networking", "Routing Protocols", "Beginner",
        { best: "O(E)", average: "O(E)", worst: "O(E)" }, "O(V)", "graph"),
      createAlgorithm(372, "Token Bucket Algorithm", "Networking", "Traffic Shaping", "Beginner",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),
      createAlgorithm(373, "Leaky Bucket Algorithm", "Networking", "Traffic Shaping", "Beginner",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),
      createAlgorithm(374, "Congestion Control Algorithm", "Networking", "Network Management", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(375, "Sliding Window Protocol", "Networking", "Data Link Layer", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(w)", "array"),
      createAlgorithm(376, "Go-Back-N Protocol", "Networking", "Data Link Layer", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(377, "Selective Repeat Protocol", "Networking", "Data Link Layer", "Intermediate",
        { best: "O(1)", average: "O(log n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(378, "Paxos Algorithm", "Distributed Systems", "Consensus", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(379, "Raft Consensus Algorithm", "Distributed Systems", "Consensus", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n²)" }, "O(n log n)", "array"),
      createAlgorithm(380, "Byzantine Fault Tolerance", "Distributed Systems", "Consensus", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n²)", "array"),

      // 30. Compression, Graphics & Misc (20) - Algorithms 381-400
      createAlgorithm(381, "Run-Length Encoding", "Compression", "Data Compression", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(382, "Arithmetic Coding", "Compression", "Data Compression", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(383, "Shannon–Fano Coding", "Compression", "Data Compression", "Intermediate",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "tree"),
      createAlgorithm(384, "JPEG Compression Algorithm", "Compression", "Image Compression", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n²)", "array"),
      createAlgorithm(385, "PNG Compression Algorithm", "Compression", "Image Compression", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(386, "Bresenham Line Algorithm", "Graphics", "Computer Graphics", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(387, "DDA Line Algorithm", "Graphics", "Computer Graphics", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(388, "Midpoint Circle Algorithm", "Graphics", "Computer Graphics", "Intermediate",
        { best: "O(r)", average: "O(r)", worst: "O(r)" }, "O(1)", "array"),
      createAlgorithm(389, "Scanline Polygon Fill", "Graphics", "Computer Graphics", "Intermediate",
        { best: "O(n·h)", average: "O(n·h)", worst: "O(n·h)" }, "O(n)", "array"),
      createAlgorithm(390, "Z-Buffer Algorithm", "Graphics", "Computer Graphics", "Intermediate",
        { best: "O(n·p)", average: "O(n·p)", worst: "O(n·p)" }, "O(w·h)", "array"),
      createAlgorithm(391, "Ray Tracing Algorithm", "Graphics", "Computer Graphics", "Advanced",
        { best: "O(n·p·o)", average: "O(n·p·o)", worst: "O(n·p·o)" }, "O(w·h)", "array"),
      createAlgorithm(392, "Image Thresholding", "Graphics", "Image Processing", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(393, "Sobel Edge Detection", "Graphics", "Image Processing", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(394, "Canny Edge Detection", "Graphics", "Image Processing", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(395, "K-D Tree Construction", "Data Structures", "Spatial Data Structures", "Advanced",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n²)" }, "O(n)", "tree"),
      createAlgorithm(396, "R-Tree Indexing", "Data Structures", "Spatial Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "tree"),
      createAlgorithm(397, "Bloom Join Algorithm", "Database", "Database Systems", "Advanced",
        { best: "O(n + m)", average: "O(n + m)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(398, "Count-Min Sketch", "Data Structures", "Probabilistic Data Structures", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(w·d)", "array"),
      createAlgorithm(399, "HyperLogLog Algorithm", "Data Structures", "Probabilistic Data Structures", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(m)", "array"),
      createAlgorithm(400, "SimHash Algorithm", "Data Mining", "Similarity Detection", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),

      // 31. Advanced Parallel & Distributed Algorithms (20) - Algorithms 401-420
      createAlgorithm(401, "MapReduce Algorithm", "Parallel Computing", "Distributed Computing", "Advanced",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(402, "Parallel Prefix Sum (Scan)", "Parallel Computing", "Parallel Algorithms", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "array"),
      createAlgorithm(403, "Parallel Merge Sort", "Parallel Computing", "Parallel Algorithms", "Intermediate",
        { best: "O(log² n)", average: "O(log² n)", worst: "O(log² n)" }, "O(n)", "array"),
      createAlgorithm(404, "Parallel Quick Sort", "Parallel Computing", "Parallel Algorithms", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(405, "Parallel Matrix Multiplication", "Parallel Computing", "Parallel Algorithms", "Advanced",
        { best: "O(n³/p)", average: "O(n³/p)", worst: "O(n³/p)" }, "O(n²)", "array"),
      createAlgorithm(406, "Parallel BFS", "Parallel Computing", "Graph Algorithms", "Advanced",
        { best: "O(d·log V)", average: "O(d·log V)", worst: "O(V + E)" }, "O(V)", "graph"),
      createAlgorithm(407, "Parallel DFS", "Parallel Computing", "Graph Algorithms", "Advanced",
        { best: "O(V/p)", average: "O(V/p)", worst: "O(V)" }, "O(V)", "graph"),
      createAlgorithm(408, "Work Stealing Algorithm", "Parallel Computing", "Task Scheduling", "Advanced",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(p)", "array"),
      createAlgorithm(409, "Fork-Join Algorithm", "Parallel Computing", "Task Scheduling", "Intermediate",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(log n)", "tree"),
      createAlgorithm(410, "Bulk Synchronous Parallel (BSP)", "Parallel Computing", "Programming Models", "Advanced",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(n/p)", "array"),
      createAlgorithm(411, "SPMD Model Algorithm", "Parallel Computing", "Programming Models", "Intermediate",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(n/p)", "array"),
      createAlgorithm(412, "Data Parallel Algorithm", "Parallel Computing", "Programming Models", "Intermediate",
        { best: "O(n/p)", average: "O(n/p)", worst: "O(n)" }, "O(n/p)", "array"),
      createAlgorithm(413, "Pipeline Parallel Algorithm", "Parallel Computing", "Programming Models", "Intermediate",
        { best: "O(n/p + p)", average: "O(n/p + p)", worst: "O(n)" }, "O(n/p)", "array"),
      createAlgorithm(414, "Load Balancing Algorithm", "Parallel Computing", "Task Scheduling", "Advanced",
        { best: "O(n)", average: "O(n log p)", worst: "O(n·p)" }, "O(p)", "array"),
      createAlgorithm(415, "Distributed Hash Table", "Distributed Systems", "Data Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n/p)", "graph"),
      createAlgorithm(416, "Chord Protocol", "Distributed Systems", "Peer-to-Peer", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(log n)", "graph"),
      createAlgorithm(417, "Kademlia Protocol", "Distributed Systems", "Peer-to-Peer", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "tree"),
      createAlgorithm(418, "Gossip Protocol", "Distributed Systems", "Communication", "Intermediate",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "graph"),
      createAlgorithm(419, "Vector Clocks", "Distributed Systems", "Synchronization", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(420, "Lamport Timestamps", "Distributed Systems", "Synchronization", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),

      // 32. Quantum & Advanced Computational Algorithms (20) - Algorithms 421-440
      createAlgorithm(421, "Shor's Algorithm", "Quantum Computing", "Quantum Algorithms", "Expert",
        { best: "O(log³ n)", average: "O(log³ n)", worst: "O(log³ n)" }, "O(log n)", "array"),
      createAlgorithm(422, "Grover's Algorithm", "Quantum Computing", "Quantum Algorithms", "Expert",
        { best: "O(√n)", average: "O(√n)", worst: "O(√n)" }, "O(log n)", "array"),
      createAlgorithm(423, "Quantum Fourier Transform", "Quantum Computing", "Quantum Algorithms", "Expert",
        { best: "O(log² n)", average: "O(log² n)", worst: "O(log² n)" }, "O(n)", "array"),
      createAlgorithm(424, "Quantum Phase Estimation", "Quantum Computing", "Quantum Algorithms", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "array"),
      createAlgorithm(425, "Quantum Annealing", "Quantum Computing", "Optimization", "Expert",
        { best: "O(√n)", average: "O(√n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(426, "VQE Algorithm", "Quantum Computing", "Quantum Algorithms", "Expert",
        { best: "O(k·p)", average: "O(k·p)", worst: "O(k·p)" }, "O(n)", "array"),
      createAlgorithm(427, "QAOA Algorithm", "Quantum Computing", "Optimization", "Expert",
        { best: "O(p·n)", average: "O(p·n)", worst: "O(p·n)" }, "O(n)", "graph"),
      createAlgorithm(428, "Strassen's Matrix Multiplication", "Mathematical", "Linear Algebra", "Advanced",
        { best: "O(n^2.807)", average: "O(n^2.807)", worst: "O(n^2.807)" }, "O(n²)", "array"),
      createAlgorithm(429, "Coppersmith–Winograd Algorithm", "Mathematical", "Linear Algebra", "Expert",
        { best: "O(n^2.376)", average: "O(n^2.376)", worst: "O(n^2.376)" }, "O(n²)", "array"),
      createAlgorithm(430, "Schönhage–Strassen Algorithm", "Mathematical", "Number Theory", "Expert",
        { best: "O(n·log n·log log n)", average: "O(n·log n·log log n)", worst: "O(n·log n·log log n)" }, "O(n)", "array"),
      createAlgorithm(431, "AKS Primality Test", "Mathematical", "Number Theory", "Expert",
        { best: "O(log^6 n)", average: "O(log^6 n)", worst: "O(log^12 n)" }, "O(log n)", "array"),
      createAlgorithm(432, "Baby-Step Giant-Step", "Mathematical", "Number Theory", "Advanced",
        { best: "O(√n)", average: "O(√n)", worst: "O(√n)" }, "O(√n)", "array"),
      createAlgorithm(433, "Tonelli–Shanks Algorithm", "Mathematical", "Number Theory", "Advanced",
        { best: "O(log² n)", average: "O(log² n)", worst: "O(log³ n)" }, "O(1)", "array"),
      createAlgorithm(434, "Berlekamp–Massey Algorithm", "Mathematical", "Coding Theory", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(435, "Reed–Solomon Encoding", "Coding Theory", "Error Correction", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(436, "Viterbi Decoding", "Coding Theory", "Error Correction", "Advanced",
        { best: "O(n·s²)", average: "O(n·s²)", worst: "O(n·s²)" }, "O(n·s)", "array"),
      createAlgorithm(437, "Turbo Code Decoding", "Coding Theory", "Error Correction", "Expert",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(438, "LDPC Code Decoding", "Coding Theory", "Error Correction", "Expert",
        { best: "O(k·e)", average: "O(k·e)", worst: "O(k·e)" }, "O(n)", "graph"),
      createAlgorithm(439, "Syndrome Decoding", "Coding Theory", "Error Correction", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(440, "List Decoding Algorithm", "Coding Theory", "Error Correction", "Expert",
        { best: "O(n²)", average: "O(n³)", worst: "O(n⁴)" }, "O(n²)", "array"),

      // 33. Bioinformatics & Computational Biology (20) - Algorithms 441-460
      createAlgorithm(441, "Needleman–Wunsch Algorithm", "Bioinformatics", "Sequence Alignment", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(442, "Smith–Waterman Algorithm", "Bioinformatics", "Sequence Alignment", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(443, "BLAST Algorithm", "Bioinformatics", "Sequence Alignment", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(444, "FASTA Algorithm", "Bioinformatics", "Sequence Alignment", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(445, "Burrows–Wheeler Transform", "Bioinformatics", "String Processing", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(446, "FM-Index Algorithm", "Bioinformatics", "String Indexing", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(447, "Suffix Array Construction", "Bioinformatics", "String Processing", "Advanced",
        { best: "O(n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
      createAlgorithm(448, "LCP Array Construction", "Bioinformatics", "String Processing", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(449, "UPGMA Algorithm", "Bioinformatics", "Phylogenetics", "Intermediate",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n²)", "tree"),
      createAlgorithm(450, "Neighbor-Joining Algorithm", "Bioinformatics", "Phylogenetics", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "tree"),
      createAlgorithm(451, "Maximum Parsimony Algorithm", "Bioinformatics", "Phylogenetics", "Advanced",
        { best: "O(n·m·k)", average: "O(n·m·k)", worst: "NP-Hard" }, "O(n·m)", "tree"),
      createAlgorithm(452, "Maximum Likelihood Estimation", "Bioinformatics", "Phylogenetics", "Expert",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(n·m)", "tree"),
      createAlgorithm(453, "Protein Folding Algorithm", "Bioinformatics", "Structural Biology", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "NP-Hard" }, "O(n³)", "array"),
      createAlgorithm(454, "Gene Prediction Algorithm", "Bioinformatics", "Genomics", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(455, "Motif Finding Algorithm", "Bioinformatics", "Genomics", "Advanced",
        { best: "O(n·m)", average: "O(n·m·k)", worst: "NP-Hard" }, "O(n·m)", "array"),
      createAlgorithm(456, "RNA Secondary Structure Prediction", "Bioinformatics", "RNA Analysis", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(457, "Genome Assembly Algorithm", "Bioinformatics", "Genomics", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "NP-Hard" }, "O(n²)", "graph"),
      createAlgorithm(458, "Variant Calling Algorithm", "Bioinformatics", "Genomics", "Advanced",
        { best: "O(n·d)", average: "O(n·d)", worst: "O(n·d)" }, "O(n)", "array"),
      createAlgorithm(459, "Haplotype Phasing Algorithm", "Bioinformatics", "Genomics", "Expert",
        { best: "O(n·m·k)", average: "O(n·m·k)", worst: "NP-Hard" }, "O(n·m)", "array"),
      createAlgorithm(460, "Population Genetics Algorithm", "Bioinformatics", "Genomics", "Advanced",
        { best: "O(n·m)", average: "O(n·m·k)", worst: "O(n·m·k)" }, "O(n·m)", "array"),

      // 34. Advanced Cryptography (20) - Algorithms 461-480
      createAlgorithm(461, "Diffie–Hellman Key Exchange", "Cryptography", "Key Exchange", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(462, "Elliptic Curve Diffie–Hellman", "Cryptography", "Key Exchange", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(463, "DSA Algorithm", "Cryptography", "Digital Signatures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(464, "ECDSA Algorithm", "Cryptography", "Digital Signatures", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(465, "Schnorr Signature", "Cryptography", "Digital Signatures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(466, "ElGamal Encryption", "Cryptography", "Public Key Cryptography", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),
      createAlgorithm(467, "Paillier Cryptosystem", "Cryptography", "Homomorphic Encryption", "Expert",
        { best: "O(log² n)", average: "O(log² n)", worst: "O(log² n)" }, "O(1)", "array"),
      createAlgorithm(468, "BGV Scheme", "Cryptography", "Homomorphic Encryption", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(469, "CKKS Scheme", "Cryptography", "Homomorphic Encryption", "Expert",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(470, "Zero-Knowledge Proof", "Cryptography", "Proof Systems", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(471, "zk-SNARK", "Cryptography", "Proof Systems", "Expert",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(472, "zk-STARK", "Cryptography", "Proof Systems", "Expert",
        { best: "O(n·log² n)", average: "O(n·log² n)", worst: "O(n·log² n)" }, "O(n·log n)", "array"),
      createAlgorithm(473, "Bulletproofs", "Cryptography", "Proof Systems", "Expert",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(log n)", "array"),
      createAlgorithm(474, "Threshold Cryptography", "Cryptography", "Secure Multi-Party Computation", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(475, "Shamir's Secret Sharing", "Cryptography", "Secret Sharing", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(476, "Verifiable Secret Sharing", "Cryptography", "Secret Sharing", "Expert",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(477, "Oblivious Transfer", "Cryptography", "Secure Multi-Party Computation", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(478, "Garbled Circuits", "Cryptography", "Secure Multi-Party Computation", "Expert",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(479, "Ring Signatures", "Cryptography", "Digital Signatures", "Expert",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(480, "Blind Signatures", "Cryptography", "Digital Signatures", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(1)", "array"),

      // 35. Advanced Computer Vision (20) - Algorithms 481-500
      createAlgorithm(481, "SIFT Algorithm", "Computer Vision", "Feature Detection", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(482, "SURF Algorithm", "Computer Vision", "Feature Detection", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(483, "ORB Algorithm", "Computer Vision", "Feature Detection", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(484, "Harris Corner Detection", "Computer Vision", "Feature Detection", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(485, "FAST Algorithm", "Computer Vision", "Feature Detection", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(486, "RANSAC Algorithm", "Computer Vision", "Model Fitting", "Advanced",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(487, "Hough Transform", "Computer Vision", "Feature Detection", "Intermediate",
        { best: "O(n·m·θ·ρ)", average: "O(n·m·θ·ρ)", worst: "O(n·m·θ·ρ)" }, "O(θ·ρ)", "array"),
      createAlgorithm(488, "Optical Flow (Lucas–Kanade)", "Computer Vision", "Motion Estimation", "Advanced",
        { best: "O(n·m·w²)", average: "O(n·m·w²)", worst: "O(n·m·w²)" }, "O(n·m)", "array"),
      createAlgorithm(489, "Horn–Schunck Optical Flow", "Computer Vision", "Motion Estimation", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(n·m)", "array"),
      createAlgorithm(490, "Mean Shift Algorithm", "Computer Vision", "Object Tracking", "Advanced",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(n)", "array"),
      createAlgorithm(491, "CAMShift Algorithm", "Computer Vision", "Object Tracking", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(n·m)", "array"),
      createAlgorithm(492, "Viola–Jones Face Detection", "Computer Vision", "Object Detection", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m·s)" }, "O(f)", "array"),
      createAlgorithm(493, "HOG Feature Extraction", "Computer Vision", "Feature Extraction", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(b·b·h)", "array"),
      createAlgorithm(494, "YOLO Algorithm", "Computer Vision", "Object Detection", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(495, "R-CNN Algorithm", "Computer Vision", "Object Detection", "Advanced",
        { best: "O(r·n·m)", average: "O(r·n·m)", worst: "O(r·n·m)" }, "O(r)", "array"),
      createAlgorithm(496, "Mask R-CNN", "Computer Vision", "Instance Segmentation", "Expert",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(497, "Semantic Segmentation (FCN)", "Computer Vision", "Semantic Segmentation", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(498, "U-Net Algorithm", "Computer Vision", "Semantic Segmentation", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(499, "GrabCut Algorithm", "Computer Vision", "Image Segmentation", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(n·m)", "array"),
      createAlgorithm(500, "Watershed Algorithm", "Computer Vision", "Image Segmentation", "Intermediate",
        { best: "O(n·m·log(n·m))", average: "O(n·m·log(n·m))", worst: "O(n·m·log(n·m))" }, "O(n·m)", "array"),

      // 36. Advanced Natural Language Processing (20) - Algorithms 501-520
      createAlgorithm(501, "Word2Vec (Skip-gram)", "NLP", "Word Embeddings", "Advanced",
        { best: "O(k·n·c)", average: "O(k·n·c)", worst: "O(k·n·c)" }, "O(v·d)", "array"),
      createAlgorithm(502, "Word2Vec (CBOW)", "NLP", "Word Embeddings", "Advanced",
        { best: "O(k·n·c)", average: "O(k·n·c)", worst: "O(k·n·c)" }, "O(v·d)", "array"),
      createAlgorithm(503, "GloVe Algorithm", "NLP", "Word Embeddings", "Advanced",
        { best: "O(k·|C|)", average: "O(k·|C|)", worst: "O(k·|C|)" }, "O(v·d)", "array"),
      createAlgorithm(504, "FastText Algorithm", "NLP", "Word Embeddings", "Advanced",
        { best: "O(k·n·c)", average: "O(k·n·c)", worst: "O(k·n·c)" }, "O(v·d)", "array"),
      createAlgorithm(505, "BERT Pretraining", "NLP", "Language Models", "Expert",
        { best: "O(n²·d)", average: "O(n²·d)", worst: "O(n²·d)" }, "O(L·d)", "array"),
      createAlgorithm(506, "GPT Training", "NLP", "Language Models", "Expert",
        { best: "O(n²·d)", average: "O(n²·d)", worst: "O(n²·d)" }, "O(L·d)", "array"),
      createAlgorithm(507, "Transformer Architecture", "NLP", "Neural Architectures", "Expert",
        { best: "O(n²·d)", average: "O(n²·d)", worst: "O(n²·d)" }, "O(n·d)", "array"),
      createAlgorithm(508, "Attention Mechanism", "NLP", "Neural Architectures", "Advanced",
        { best: "O(n²·d)", average: "O(n²·d)", worst: "O(n²·d)" }, "O(n·d)", "array"),
      createAlgorithm(509, "CRF (Conditional Random Field)", "NLP", "Sequence Labeling", "Advanced",
        { best: "O(n·s²)", average: "O(n·s²)", worst: "O(n·s²)" }, "O(n·s)", "array"),
      createAlgorithm(510, "Named Entity Recognition (BiLSTM-CRF)", "NLP", "Information Extraction", "Advanced",
        { best: "O(n·d²)", average: "O(n·d²)", worst: "O(n·d²)" }, "O(n·d)", "array"),
      createAlgorithm(511, "Dependency Parsing (Arc-Standard)", "NLP", "Syntactic Analysis", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n³)" }, "O(n)", "tree"),
      createAlgorithm(512, "Constituency Parsing (CKY)", "NLP", "Syntactic Analysis", "Advanced",
        { best: "O(n³·|G|)", average: "O(n³·|G|)", worst: "O(n³·|G|)" }, "O(n²)", "tree"),
      createAlgorithm(513, "Beam Search Decoding", "NLP", "Sequence Generation", "Intermediate",
        { best: "O(n·b·v)", average: "O(n·b·v)", worst: "O(n·b·v)" }, "O(b·n)", "tree"),
      createAlgorithm(514, "Seq2Seq with Attention", "NLP", "Sequence Generation", "Advanced",
        { best: "O(n·m·d)", average: "O(n·m·d)", worst: "O(n·m·d)" }, "O(n·d)", "array"),
      createAlgorithm(515, "Neural Machine Translation", "NLP", "Machine Translation", "Expert",
        { best: "O(n²·d)", average: "O(n²·d)", worst: "O(n²·d)" }, "O(n·d)", "array"),
      createAlgorithm(516, "BPE Tokenization", "NLP", "Text Preprocessing", "Intermediate",
        { best: "O(n·v)", average: "O(n·v·log v)", worst: "O(n·v²)" }, "O(v)", "array"),
      createAlgorithm(517, "SentencePiece Algorithm", "NLP", "Text Preprocessing", "Advanced",
        { best: "O(n·v)", average: "O(n·v)", worst: "O(n·v)" }, "O(v)", "tree"),
      createAlgorithm(518, "TF-IDF Vectorization", "NLP", "Text Representation", "Beginner",
        { best: "O(n·d)", average: "O(n·d)", worst: "O(n·d)" }, "O(d·v)", "array"),
      createAlgorithm(519, "LSA (Latent Semantic Analysis)", "NLP", "Topic Modeling", "Intermediate",
        { best: "O(n·d·k)", average: "O(n·d·k)", worst: "O(min(n²d, nd²))" }, "O(d·k)", "array"),
      createAlgorithm(520, "TextRank Algorithm", "NLP", "Text Summarization", "Intermediate",
        { best: "O(n²)", average: "O(k·n²)", worst: "O(k·n²)" }, "O(n²)", "graph"),

      // 37. Robotics & Control Systems (20) - Algorithms 521-540
      createAlgorithm(521, "PID Controller", "Robotics", "Control Systems", "Beginner",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),
      createAlgorithm(522, "LQR (Linear Quadratic Regulator)", "Robotics", "Control Systems", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(523, "MPC (Model Predictive Control)", "Robotics", "Control Systems", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(524, "Extended Kalman Filter", "Robotics", "State Estimation", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(525, "Unscented Kalman Filter", "Robotics", "State Estimation", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(526, "SLAM (FastSLAM)", "Robotics", "Mapping", "Expert",
        { best: "O(M·log N)", average: "O(M·log N)", worst: "O(M·N)" }, "O(M·N)", "array"),
      createAlgorithm(527, "EKF-SLAM", "Robotics", "Mapping", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(528, "Graph-SLAM", "Robotics", "Mapping", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "graph"),
      createAlgorithm(529, "RRT (Rapidly-exploring Random Tree)", "Robotics", "Motion Planning", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "tree"),
      createAlgorithm(530, "RRT* Algorithm", "Robotics", "Motion Planning", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "tree"),
      createAlgorithm(531, "PRM (Probabilistic Roadmap)", "Robotics", "Motion Planning", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "graph"),
      createAlgorithm(532, "Potential Field Method", "Robotics", "Motion Planning", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(533, "Dynamic Window Approach", "Robotics", "Local Planning", "Intermediate",
        { best: "O(v·ω)", average: "O(v·ω)", worst: "O(v·ω)" }, "O(v·ω)", "array"),
      createAlgorithm(534, "TEB (Timed Elastic Band)", "Robotics", "Local Planning", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(535, "Inverse Kinematics (Jacobian)", "Robotics", "Kinematics", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(536, "Forward Kinematics", "Robotics", "Kinematics", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(537, "Trajectory Optimization", "Robotics", "Motion Planning", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(538, "ICP (Iterative Closest Point)", "Robotics", "Registration", "Advanced",
        { best: "O(k·n·m)", average: "O(k·n·m)", worst: "O(k·n·m)" }, "O(n+m)", "array"),
      createAlgorithm(539, "Visual Odometry", "Robotics", "Localization", "Advanced",
        { best: "O(n·f)", average: "O(n·f)", worst: "O(n²·f)" }, "O(n)", "array"),
      createAlgorithm(540, "Bundle Adjustment", "Robotics", "3D Reconstruction", "Expert",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),

      // 38. Time Series & Signal Processing (20) - Algorithms 541-560
      createAlgorithm(541, "FFT (Fast Fourier Transform)", "Signal Processing", "Frequency Analysis", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(542, "Inverse FFT", "Signal Processing", "Frequency Analysis", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(543, "Discrete Wavelet Transform", "Signal Processing", "Time-Frequency Analysis", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(544, "Continuous Wavelet Transform", "Signal Processing", "Time-Frequency Analysis", "Advanced",
        { best: "O(n·s)", average: "O(n·s)", worst: "O(n·s)" }, "O(n·s)", "array"),
      createAlgorithm(545, "STFT (Short-Time Fourier Transform)", "Signal Processing", "Time-Frequency Analysis", "Intermediate",
        { best: "O(w·n·log w)", average: "O(w·n·log w)", worst: "O(w·n·log w)" }, "O(w·n)", "array"),
      createAlgorithm(546, "ARIMA Model", "Time Series", "Forecasting", "Advanced",
        { best: "O(n·p²)", average: "O(n·p²)", worst: "O(n·p²)" }, "O(p)", "array"),
      createAlgorithm(547, "SARIMA Model", "Time Series", "Forecasting", "Advanced",
        { best: "O(n·p²)", average: "O(n·p²)", worst: "O(n·p²)" }, "O(p)", "array"),
      createAlgorithm(548, "Exponential Smoothing", "Time Series", "Forecasting", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(549, "Holt-Winters Algorithm", "Time Series", "Forecasting", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(s)", "array"),
      createAlgorithm(550, "Prophet Algorithm", "Time Series", "Forecasting", "Advanced",
        { best: "O(n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(551, "DTW (Dynamic Time Warping)", "Time Series", "Similarity Measurement", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(552, "SAX (Symbolic Aggregate Approximation)", "Time Series", "Representation", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(w)", "array"),
      createAlgorithm(553, "Matrix Profile Algorithm", "Time Series", "Motif Discovery", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(554, "Granger Causality Test", "Time Series", "Causality Analysis", "Advanced",
        { best: "O(n·p²)", average: "O(n·p²)", worst: "O(n·p²)" }, "O(p)", "array"),
      createAlgorithm(555, "Autocorrelation Analysis", "Time Series", "Statistical Analysis", "Intermediate",
        { best: "O(n·k)", average: "O(n·k)", worst: "O(n·k)" }, "O(k)", "array"),
      createAlgorithm(556, "Spectral Analysis", "Signal Processing", "Frequency Analysis", "Intermediate",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(557, "Hilbert Transform", "Signal Processing", "Analytic Signals", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(558, "Wiener Filter", "Signal Processing", "Noise Reduction", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(559, "Adaptive Filtering (LMS)", "Signal Processing", "Adaptive Systems", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(m)", "array"),
      createAlgorithm(560, "Matched Filter", "Signal Processing", "Detection", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(m)", "array"),

      // 39. Financial Algorithms (20) - Algorithms 561-580
      createAlgorithm(561, "Black–Scholes Model", "Finance", "Option Pricing", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),
      createAlgorithm(562, "Monte Carlo Simulation", "Finance", "Risk Analysis", "Advanced",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(k)", "array"),
      createAlgorithm(563, "Binomial Option Pricing", "Finance", "Option Pricing", "Intermediate",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n)", "tree"),
      createAlgorithm(564, "GARCH Model", "Finance", "Volatility Modeling", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(565, "VAR (Value at Risk)", "Finance", "Risk Measurement", "Intermediate",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(566, "CVaR (Conditional VaR)", "Finance", "Risk Measurement", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n·log n)" }, "O(n)", "array"),
      createAlgorithm(567, "CAPM (Capital Asset Pricing Model)", "Finance", "Asset Pricing", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(568, "Fama–French Model", "Finance", "Asset Pricing", "Advanced",
        { best: "O(n·f)", average: "O(n·f)", worst: "O(n·f)" }, "O(f)", "array"),
      createAlgorithm(569, "APT (Arbitrage Pricing Theory)", "Finance", "Asset Pricing", "Advanced",
        { best: "O(n·f)", average: "O(n·f)", worst: "O(n·f)" }, "O(f)", "array"),
      createAlgorithm(570, "Portfolio Optimization (Markowitz)", "Finance", "Portfolio Management", "Advanced",
        { best: "O(n³)", average: "O(n³)", worst: "O(n³)" }, "O(n²)", "array"),
      createAlgorithm(571, "Sharpe Ratio Calculation", "Finance", "Performance Measurement", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(572, "Kelly Criterion", "Finance", "Position Sizing", "Intermediate",
        { best: "O(1)", average: "O(1)", worst: "O(1)" }, "O(1)", "array"),
      createAlgorithm(573, "Pairs Trading Strategy", "Finance", "Statistical Arbitrage", "Advanced",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n)", "array"),
      createAlgorithm(574, "Mean Reversion Strategy", "Finance", "Trading Strategies", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(w)", "array"),
      createAlgorithm(575, "Momentum Trading Strategy", "Finance", "Trading Strategies", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(w)", "array"),
      createAlgorithm(576, "VWAP Algorithm", "Finance", "Execution Algorithms", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(577, "TWAP Algorithm", "Finance", "Execution Algorithms", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(578, "Credit Risk Scoring", "Finance", "Credit Analysis", "Advanced",
        { best: "O(n·f)", average: "O(n·f)", worst: "O(n·f)" }, "O(f)", "array"),
      createAlgorithm(579, "Fraud Detection Algorithm", "Finance", "Risk Management", "Advanced",
        { best: "O(n·log n)", average: "O(n·log n)", worst: "O(n²)" }, "O(n)", "array"),
      createAlgorithm(580, "High-Frequency Trading Algorithm", "Finance", "Algorithmic Trading", "Expert",
        { best: "O(log n)", average: "O(log n)", worst: "O(log n)" }, "O(n)", "array"),

      // 40. Miscellaneous Advanced Algorithms (20) - Algorithms 581-600
      createAlgorithm(581, "Locality-Sensitive Hashing", "Data Structures", "Similarity Search", "Advanced",
        { best: "O(1)", average: "O(1)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(582, "MinHash Algorithm", "Data Mining", "Similarity Detection", "Advanced",
        { best: "O(k·n)", average: "O(k·n)", worst: "O(k·n)" }, "O(k)", "array"),
      createAlgorithm(583, "Jaccard Similarity", "Data Mining", "Similarity Measurement", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(584, "Cosine Similarity", "Data Mining", "Similarity Measurement", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(585, "Edit Distance (Levenshtein)", "String", "String Similarity", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(586, "Hamming Distance", "String", "String Similarity", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(587, "Longest Increasing Subsequence", "Dynamic Programming", "Sequence Problems", "Intermediate",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
      createAlgorithm(588, "Longest Common Subsequence", "Dynamic Programming", "Sequence Problems", "Intermediate",
        { best: "O(n·m)", average: "O(n·m)", worst: "O(n·m)" }, "O(n·m)", "array"),
      createAlgorithm(589, "Maximum Subarray Sum (Kadane)", "Dynamic Programming", "Array Problems", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(590, "Reservoir Sampling", "Randomized", "Sampling", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(k)", "array"),
      createAlgorithm(591, "Fisher–Yates Shuffle", "Randomized", "Shuffling", "Beginner",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(1)", "array"),
      createAlgorithm(592, "Skip List Operations", "Data Structures", "Search Structures", "Advanced",
        { best: "O(log n)", average: "O(log n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(593, "Trie Operations", "Data Structures", "String Structures", "Intermediate",
        { best: "O(m)", average: "O(m)", worst: "O(m)" }, "O(n·m)", "tree"),
      createAlgorithm(594, "Suffix Trie Construction", "String", "String Indexing", "Advanced",
        { best: "O(n²)", average: "O(n²)", worst: "O(n²)" }, "O(n²)", "tree"),
      createAlgorithm(595, "Aho–Corasick Automaton", "String", "Pattern Matching", "Advanced",
        { best: "O(n + m + z)", average: "O(n + m + z)", worst: "O(n + m + z)" }, "O(m·σ)", "tree"),
      createAlgorithm(596, "Z-Algorithm", "String", "Pattern Matching", "Intermediate",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(597, "Manacher's Algorithm", "String", "Palindrome Finding", "Advanced",
        { best: "O(n)", average: "O(n)", worst: "O(n)" }, "O(n)", "array"),
      createAlgorithm(598, "Rabin–Karp Algorithm", "String", "Pattern Matching", "Intermediate",
        { best: "O(n + m)", average: "O(n + m)", worst: "O(n·m)" }, "O(1)", "array"),
      createAlgorithm(599, "Convex Hull (Gift Wrapping)", "Computational Geometry", "Geometric Algorithms", "Intermediate",
        { best: "O(n·h)", average: "O(n·h)", worst: "O(n²)" }, "O(h)", "array"),
      createAlgorithm(600, "Closest Pair of Points", "Computational Geometry", "Geometric Algorithms", "Advanced",
        { best: "O(n log n)", average: "O(n log n)", worst: "O(n log n)" }, "O(n)", "array"),
    ];

    for (const algo of allAlgorithms) {
      await ctx.db.insert("algorithms", algo);
    }

    return {
      success: true,
      count: allAlgorithms.length,
      message: `Successfully added algorithms 401-600 (${allAlgorithms.length} algorithms)!`,
    };
  },
});
